import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Narbar from "./components/narbar/Narbar";
import ClientOnly from "./components/ClientOnly";
import RegisterModal from "./components/modal/RegisterModal";
import ToasterProvider from "./providers/ToasterProvider";
import Footer from "./components/Footer";

const fontNunito = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={fontNunito.className}
      >
      <ClientOnly>
        <ToasterProvider/>
        <RegisterModal/>
        <Narbar/>
      </ClientOnly>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
